version: '3.8'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 
      
volumes:
    mongo_data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: C:\srv\mongo\data\